"""core data tables

Revision ID: 23687d742700
Revises: 554787cd3c42
Create Date: 2026-07-07 00:09:50.298570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23687d742700'
down_revision = '554787cd3c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('market', sa.String(length=60), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('rules_en', sa.JSON(), nullable=False),
    sa.Column('name_zh', sa.String(length=120), nullable=True),
    sa.Column('summary_zh', sa.Text(), nullable=True),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('rules_zh', sa.JSON(), nullable=True),
    sa.Column('name_es', sa.String(length=120), nullable=True),
    sa.Column('summary_es', sa.Text(), nullable=True),
    sa.Column('description_es', sa.Text(), nullable=True),
    sa.Column('rules_es', sa.JSON(), nullable=True),
    sa.Column('name_fr', sa.String(length=120), nullable=True),
    sa.Column('summary_fr', sa.Text(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('rules_fr', sa.JSON(), nullable=True),
    sa.Column('name_de', sa.String(length=120), nullable=True),
    sa.Column('summary_de', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('rules_de', sa.JSON(), nullable=True),
    sa.Column('name_ja', sa.String(length=120), nullable=True),
    sa.Column('summary_ja', sa.Text(), nullable=True),
    sa.Column('description_ja', sa.Text(), nullable=True),
    sa.Column('rules_ja', sa.JSON(), nullable=True),
    sa.Column('name_ko', sa.String(length=120), nullable=True),
    sa.Column('summary_ko', sa.Text(), nullable=True),
    sa.Column('description_ko', sa.Text(), nullable=True),
    sa.Column('rules_ko', sa.JSON(), nullable=True),
    sa.Column('is_curated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_user_id'), ['user_id'], unique=False)

    op.create_table('report_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('user_playbooks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=False),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'playbook_id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'external_id', name='uq_trades_user_source_external')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    op.create_table('trade_tags',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('trade_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_tags')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))

    op.drop_table('trades')
    op.drop_table('user_playbooks')
    with op.batch_alter_table('report_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_snapshots_user_id'))

    op.drop_table('report_snapshots')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_user_id'))

    op.drop_table('import_batches')
    op.drop_table('tags')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
