"""trades money columns to numeric

Revision ID: 66024fdca78e
Revises: 571de3dc9a30
Create Date: 2026-07-11 22:54:56.553136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66024fdca78e'
down_revision = '571de3dc9a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
        batch_op.alter_column('entry_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
        batch_op.alter_column('exit_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('fees',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('fees',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('exit_price',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('entry_price',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
